"""Marshmallow schemas for timetable models.

Autogenerated with marshmallow-mongoengine.
"""
from marshmallow import fields
from marshmallow_mongoengine import ModelSchema

import gator.core.models.timetable as timetable


class TimeSchema(ModelSchema):
    """Marshmallow schema for the :class:`Time` model."""

    class Meta:
        """Meta class for TimeSchema."""

        model = timetable.Time


class SessionSchema(ModelSchema):
    """Marshmallow schema for the :class:`Session` model."""

    class Meta:
        """Meta class for SessionSchema."""

        model = timetable.Session


class WeeklyRepetitionScheduleSchema(ModelSchema):
    """Marshmallow schema for the :class:`WeeklyRepetitionSchedule` model."""

    class Meta:
        """Meta class for WeeklyRepetitionScheduleSchema."""

        model = timetable.WeeklyRepetitionSchedule


class SectionMeetingSchema(ModelSchema):
    """Marshmallow schema for the :class:`SectionMeeting` model."""

    class Meta:
        """Meta class for SectionMeetingSchema."""

        model = timetable.SectionMeeting


class InstructorSchema(ModelSchema):
    """Marshmallow schema for the :class:`Instructor` model."""

    class Meta:
        """Meta class for InstructorSchema."""

        model = timetable.Instructor


class EnrolmentInfoSchema(ModelSchema):
    """Marshmallow schema for the :class:`EnrolmentInfo` model."""

    class Meta:
        """Meta class for EnrolmentInfoSchema."""

        model = timetable.EnrolmentInfo


class SectionSchema(ModelSchema):
    """Marshmallow schema for the :class:`Section` model."""

    class Meta:
        """Meta class for SectionSchema."""

        model = timetable.Section
        # Exclude the 'teaching_method' and 'delivery_modes' fields because they
        # are enum fields that are not supported by marshmallow-mongoengine
        model_skip_values = (timetable.TeachingMethod, timetable.SectionDeliveryMode)

    # Manually add the 'teaching_method' and 'delivery_modes' fields
    teaching_method = fields.Enum(timetable.TeachingMethod)
    delivery_modes = fields.List(fields.Enum(timetable.SectionDeliveryMode))


class CategoricalRequirementSchema(ModelSchema):
    """Marshmallow schema for the :class:`CategoricalRequirement` model."""

    class Meta:
        """Meta class for CategoricalRequirementSchema."""

        model = timetable.CategoricalRequirement


class CourseSchema(ModelSchema):
    """Marshmallow schema for the :class:`Course` model."""

    class Meta:
        """Meta class for CourseSchema."""

        model = timetable.Course
